name: Deploy Beta Docker Image to GHCR

on:
  push:
    branches:
      - beta
      - localai
  workflow_dispatch:

jobs:
      push-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Make repo lowercase'
            run: |
              echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
              
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@72f2cec99f417b1a1c5e2e88945068983b7965f9

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GH_TOKEN}}

          - name: 'Build & Publish Docker Image'
            run: |
              docker build . --tag "ghcr.io/${REPO}:beta"
              docker push "ghcr.io/${REPO}:beta"
